// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-NiKIqFZ0uUKabdkLcm6jJx-XXwoK4Lg',
    appId: '1:919999061236:web:ac9f3b6dceb921659412a1',
    messagingSenderId: '919999061236',
    projectId: 'projet-de2d8',
    authDomain: 'projet-de2d8.firebaseapp.com',
    databaseURL: 'https://projet-de2d8-default-rtdb.firebaseio.com',
    storageBucket: 'projet-de2d8.appspot.com',
    measurementId: 'G-391QZ1L92C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7pv037dGyzhlnLPPPmsQDaW5TgwLJLxI',
    appId: '1:919999061236:android:9723fb1ada61db479412a1',
    messagingSenderId: '919999061236',
    projectId: 'projet-de2d8',
    databaseURL: 'https://projet-de2d8-default-rtdb.firebaseio.com',
    storageBucket: 'projet-de2d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJkVIoHywc_QLvV4yKano0MPk3FRCn1ro',
    appId: '1:919999061236:ios:f55f488b18a9dc3d9412a1',
    messagingSenderId: '919999061236',
    projectId: 'projet-de2d8',
    databaseURL: 'https://projet-de2d8-default-rtdb.firebaseio.com',
    storageBucket: 'projet-de2d8.appspot.com',
    iosClientId: '919999061236-t27le0nfqqh00r4kosqqiaupr1m2s55f.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
